In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Importamos las librerias de las que haremos uso

In [2]:
import os
import numpy as np
from matplotlib import pyplot
from scipy import optimize
import pandas as pd
from sklearn import preprocessing
import csv
%matplotlib inline

# Preprocesamiento de datos con pandas

In [3]:
#cargado de datos
df = pd.read_csv("/content/drive/MyDrive/IA/dataset/adult.csv", sep=",")

diccionario = {"Private": 1, "Self-emp-not-inc": 2, "Local-gov":3, "?":4, "State-gov":5, "Self-emp-inc":6, "Federal-gov":7, "Without-pay":8, "Never-worked":9}
df["workclass"] = df["workclass"].replace(diccionario)

diccionario1 = {"HS-grad": 1, "Some-college": 2, "Bachelors":3, "Masters":4, "Assoc-voc":5, "11th":6, "Assoc-acdm":7, "10th":8, "7th-8th":9, "Prof-school":10,
                "9th":11, "12th":12, "Doctorate":13, "5th-6th":14, "1st-4th":15, "Preschool":16}
df["education"] = df["education"].replace(diccionario1)

diccionario2 = {"Married-civ-spouse": 1, "Never-married": 2, "Divorced":3, "Separated":4, "Widowed":5, "Married-spouse-absent":6, "Married-AF-spouse":7}
df["marital.status"] = df["marital.status"].replace(diccionario2)

diccionario3 = {"Prof-specialty": 1, "Craft-repair": 2, "Exec-managerial":3, "Adm-clerical":4, "Sales":5, "Other-service":6, "Machine-op-inspct":7, "?":8,
                "Transport-moving":9, "Handlers-cleaners":10, "Farming-fishing":11, "Tech-support":12, "Protective-serv":13, "Priv-house-serv":14, "Armed-Forces":15}
df["occupation"] = df["occupation"].replace(diccionario3)

diccionario4 = {"Husband": 1, "Not-in-family": 2, "Own-child":3, "Unmarried":4, "Wife":5, "Other-relative":6}
df["relationship"] = df["relationship"].replace(diccionario4)

diccionario5 = {"White": 1, "Black": 2, "Asian-Pac-Islander":3, "Amer-Indian-Eskimo":4, "Other":5}
df["race"] = df["race"].replace(diccionario5)

diccionario6 = {"Male": 1, "Female": 2}
df["sex"] = df["sex"].replace(diccionario6)

diccionario7 = {"?": 0,"United-States": 0,"Mexico": 0,"Philippines": 0,"Germany": 0,"Canada": 0,"Puerto-Rico": 0,"El-Salvador": 0,"India": 0,"Cuba": 0,"England": 0,"Jamaica": 0,
                "South": 0,"China": 0, "Italy": 1, "Dominican-Republic": 1, "Vietnam": 1, "Guatemala": 1, "Japan": 1, "Poland": 1, "Columbia": 1, "Taiwan": 1, "Haiti": 1, "Iran": 1, "Portugal": 1,
                "Nicaragua": 1, "Peru": 1, "Greece": 1, "Holand-Netherlands": 2, "France": 2, "Ecuador": 2, "Ireland": 2, "Hong": 2,"Trinadad&Tobago": 2, "Cambodia": 2,
                "Laos": 2, "Thailand": 2, "Yugoslavia": 2, "Outlying-US(Guam-USVI-etc)": 2, "Honduras": 2, "Hungary": 2, "Scotland": 2}
df["native.country"] = df["native.country"].replace(diccionario7)
#se eliminan los datos que entran en conflicto con las operaciones
df = df.drop('income', axis=1)
df.drop_duplicates()
df.dropna(axis=0, thresh=2) #Elimina filas con n o más valores nulos.

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
0,90,4,77053,1,9,5,8,2,1,2,0,4356,40,0
1,82,1,132870,1,9,5,3,2,1,2,0,4356,18,0
2,66,4,186061,2,10,5,8,4,2,2,0,4356,40,0
3,54,1,140359,9,4,3,7,4,1,2,0,3900,40,0
4,41,1,264663,2,10,4,1,3,1,2,0,3900,40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,1,310152,2,10,2,13,2,1,1,0,0,40,0
32557,27,1,257302,7,12,1,12,5,1,2,0,0,38,0
32558,40,1,154374,1,9,1,7,1,1,1,0,0,40,0
32559,58,1,151910,1,9,5,4,4,1,2,0,0,40,0
32560,22,1,201490,1,9,2,4,3,1,1,0,0,20,0

In [ ]:
df["native.country"].value_counts()

0    31593
1      724
2      244
Name: native.country, dtype: int64

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  int64
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  int64
 4   education.num   32561 non-null  int64
 5   marital.status  32561 non-null  int64
 6   occupation      32561 non-null  int64
 7   relationship    32561 non-null  int64
 8   race            32561 non-null  int64
 9   sex             32561 non-null  int64
 10  capital.gain    32561 non-null  int64
 11  capital.loss    32561 non-null  int64
 12  hours.per.week  32561 non-null  int64
 13  native.country  32561 non-null  int64
dtypes: int64(14)
memory usage: 3.5 MB
None

# Cargando los valores ya procesados a las variables correspondientes

In [4]:
# La entrada es de 14 elemento contando con x0
input_layer_size  = 14

# 10 etiquetas, de 1 a 10 (tomar en cuenta que se asigna "0" a la etiqueta 10)
num_labels = 3

X = df.iloc[:26048, :-1]
X_test = df.iloc[6512:, :-1]
y = df.iloc[:26048, df.columns.get_loc("native.country")]
y_test = df.iloc[6512:, df.columns.get_loc("native.country")]

In [ ]:
print(X.iloc[0,: ])
print(y)

age                  90
workclass             4
fnlwgt            77053
education             1
education.num         9
marital.status        5
occupation            8
relationship          2
race                  1
sex                   2
capital.gain          0
capital.loss       4356
hours.per.week       40
Name: 0, dtype: int64
0        0
1        0
2        0
3        0
4        0
        ..
26043    0
26044    0
26045    0
26046    0
26047    0
Name: native.country, Length: 26048, dtype: int64

# Funcion de normalizacion

In [5]:
def  featureNormalize(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis = 0)
    sigma = np.std(X, axis = 0)
    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma

In [6]:
X_norm, mu, sigma = featureNormalize(X)

In [7]:
m, n = X.shape
X = X_norm

# Funcion sigmoide

In [8]:
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

# Funcion costo

In [9]:
def lrCostFunction(theta, X, y, lambda_):

    m = y.size
    if y.dtype == bool:
        y = y.astype(int)

    J = 0
    grad = np.zeros(theta.shape)

    h = sigmoid(X.dot(theta.T))

    temp = theta
    temp[0] = 0
    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))

    grad = (1 / m) * (h - y).dot(X)
    grad = grad + (lambda_ / m) * temp

    return J, grad

In [10]:
def oneVsAll(X, y, num_labels, lambda_):
    m, n = X.shape

    all_theta = np.zeros((num_labels, n + 1))
    X = np.concatenate([np.ones((m, 1)), X], axis=1)

    for c in np.arange(num_labels):
        initial_theta = np.zeros(n + 1)
        options = {'maxiter': 50}
        res = optimize.minimize(lrCostFunction,
                                initial_theta,
                                (X, (y == c), lambda_),
                                jac=True,
                                method='CG',
                                options=options)

        all_theta[c] = res.x

    return all_theta

In [11]:
lambda_ = 0.1
all_theta = oneVsAll(X, y, num_labels, lambda_)
print(all_theta.shape)

(3, 14)

In [ ]:
print(all_theta)

[[ 3.71182020e+00 -3.23481195e-02  1.31576613e-01 -7.83070324e-02
  -2.87359770e-01  4.32942413e-02 -3.80130804e-02  2.93928379e-02
  -1.69653235e-01 -3.98545162e-01  6.96755539e-02  6.02231923e-02
   4.01378915e-02 -5.86664258e-02]
 [-3.99374755e+00  1.37034641e-02 -1.13573452e-01  9.36374837e-02
   3.23779937e-01 -6.48823458e-02  5.84507045e-02 -3.80341766e-02
   1.86752372e-01  3.76002177e-01 -1.05669990e-01 -2.82477232e-02
  -4.69128878e-02  4.17378126e-02]
 [-5.21422867e+00  1.00828156e-01 -1.78971962e-01  1.25822757e-02
   1.00741467e-01  7.23740101e-02 -4.36352625e-02  2.85856828e-03
   8.87568330e-02  4.10139879e-01  6.79531713e-02 -3.78191338e-01
  -2.22171040e-02  1.09439396e-01]]

# Funcion prediccion

In [12]:
def predictOneVsAll(all_theta, X):

    m = X.shape[0];
    num_labels = all_theta.shape[0]

    p = np.zeros(m)

    # Add ones to the X data matrix
    X = np.concatenate([np.ones((m, 1)), X], axis=1)
    p = np.argmax(sigmoid(X.dot(all_theta.T)), axis = 1)

    return p

# Prediccion

In [13]:
print(X.shape)
pred = predictOneVsAll(all_theta, X)
print('Precision del conjuto de entrenamiento: {:.2f}%'.format(np.mean(pred == y) * 100))
XPrueba = X_test.copy()
print(XPrueba.shape)
XPrueba = np.concatenate([np.ones((26049, 1)), XPrueba], axis=1)
print(XPrueba.shape)
p = np.argmax(sigmoid(XPrueba.dot(all_theta.T)), axis = 1)
print(p)
print(y_test)

(26048, 13)
Precision del conjuto de entrenamiento: 97.08%
(26049, 13)
(26049, 14)
[1 1 1 ... 1 1 1]
6512     0
6513     1
6514     1
6515     0
6516     0
        ..
32556    0
32557    0
32558    0
32559    0
32560    0
Name: native.country, Length: 26049, dtype: int64

<ipython-input-8-478bf6890dec>:2: RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-z))

In [14]:
def costFunction(theta, X, y):
    # Inicializar algunos valores utiles
    m = y.size  # numero de ejemplos de entrenamiento

    J = 0
    grad = np.zeros(theta.shape)

    h = sigmoid(X.dot(theta.T))

    J = (1 / m) * np.sum(-y.dot(np.log(h)) - (1 - y).dot(np.log(1 - h)))
    grad = (1 / m) * (h - y).dot(X)

    return J, grad

In [15]:
# Inicializacion de parametros de ajuste
initial_theta = np.zeros(n)
print(initial_theta)
cost, grad = costFunction(initial_theta, X, y)

print('Costo en theta inicial (zeros): {:.3f}'.format(cost))
print('Costo esperado (aproximado): 0.693\n')
print(grad)
print('Gradiente en theta inicial (zeros):')
print('\t[{:.4f}, {:.4f}, {:.4f}]'.format(*grad))
print('Gradiente esperado (aproximado):\n\t[-0.1000, -12.0092, -11.2628]\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Costo en theta inicial (zeros): 0.693
Costo esperado (aproximado): 0.693

age               0.000720
workclass         0.004235
fnlwgt           -0.002639
education        -0.012868
education.num     0.006920
marital.status   -0.004319
occupation       -0.001002
relationship     -0.007699
race             -0.030442
sex              -0.002194
capital.gain      0.001964
capital.loss      0.001533
hours.per.week   -0.000278
dtype: float64
Gradiente en theta inicial (zeros):
	[0.0007, 0.0042, -0.0026]
Gradiente esperado (aproximado):
	[-0.1000, -12.0092, -11.2628]

In [16]:
# Calcula y muestra el costo y el gradiente con valores de theta diferentes a cero

test_theta = np.array([90,4,77053,1,9,5,8,2,1,2,0,4356,40])
#test_theta = np.array([-11.74749157, 0.09927308, 0.09316497])
print(test_theta)
cost, grad = costFunction(test_theta, X, y)

print('Costo en theta prueba: {:.3f}'.format(cost))
print('Costo esperado (aproximado): 0.218\n')

print('Gradiente en theta prueba:')
print('\t[{:.3f}, {:.3f}, {:.3f}]'.format(*grad))
print('Gradiente esperado (aproximado):\n\t[0.043, 2.566, 2.647]')

[   90     4 77053     1     9     5     8     2     1     2     0  4356
    40]
Costo en theta prueba: nan
Costo esperado (aproximado): 0.218

Gradiente en theta prueba:
	[-0.036, -0.007, 0.364]
Gradiente esperado (aproximado):
	[0.043, 2.566, 2.647]

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [17]:
# Establecer las opciones para optimize.minimize
options= {'maxiter': 1000}

# revisar la documentacion de scipy's optimize.minimize para mayor descripcion de los parametros
# La funcion devuekve un objeto `OptimizeResult`
# Se utiliza el algoritmo de Newton truncado para la optimización.
res = optimize.minimize(costFunction,
                        initial_theta,
                        (X, y),
                        jac=True,
                        method='TNC',
                        options=options)

# la propiedad fun del objeto devuelto por `OptimizeResult`
# contiene el valor del costFunction de un theta optimizado
cost = res.fun

# Theta optimizada esta en la propiedad x
theta = res.x

# Imprimir theta en la pantalla
print('Costo con un valor de theta encontrado por optimize.minimize: {:.3f}'.format(cost))
print('Costo esperado (aproximado): 0.203\n');

print('theta:')
print('\t[{:.3f}, {:.3f}, {:.3f}]'.format(*theta))
print('Theta esperado (aproximado):\n\t[-25.161, 0.206, 0.201]')

Costo con un valor de theta encontrado por optimize.minimize: 0.691
Costo esperado (aproximado): 0.203

theta:
	[0.007, -0.019, 0.007]
Theta esperado (aproximado):
	[-25.161, 0.206, 0.201]

<ipython-input-17-0dfcfa2e2ef1>:7: OptimizeWarning: Unknown solver options: maxiter
  res = optimize.minimize(costFunction,

In [18]:
def predict(theta, X):
    m = X.shape[0] # Numero de ejemplo de entrenamiento

    p = np.zeros(m)

    p = np.round(sigmoid(X.dot(theta.T)))
    return p

In [19]:
#  Predice la probabilidad de ingreso para un estudiante con nota de 45 en el examen 1 y nota de 85 en el examen 2
prob = sigmoid(np.dot([90,4,77053,1,9,5,8,2,1,2,0,4356,40], theta))
print('Para un estudiante con notas de 45 y 85, se predice una probabilidad de admisión de: {:.3f}%'.format(prob))
print('Valor esperado: 0.775 +/- 0.002\n')

# Compute accuracy on our training set
p = predict(theta, X)
print('Precisión de entrenamiento: {:.2f} %'.format(np.mean(p == y) * 100))
print('Precisión esperada (aproximadamente): 89.00 %')

Para un estudiante con notas de 45 y 85, se predice una probabilidad de admisión de: 1.000%
Valor esperado: 0.775 +/- 0.002

Precisión de entrenamiento: 71.25 %
Precisión esperada (aproximadamente): 89.00 %